# Generated by Django 5.2.4 on 2025-08-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
