# Generated by Django 5.2.4 on 2025-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_fullname_profile_gender_profile_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
