# Generated by Django 5.2.4 on 2025-08-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('movie', 'Movie'), ('tvshow', 'TV Show'), ('podcast', 'Podcast'), ('documentary', 'Documentary')], max_length=20),
        ),
    ]
